version: '3'

services:
    alice:
        hostname: alice
        build:
            context: ../../
        ports:
            - 5000

    bob:
        hostname: bob
        build:
            context: ../../
        ports:
            - 5000

    log:
        build:
            context: ../../syslog
        command: python3 -u /syslogd.py --unix
        volumes:
            - ./tmp:/tmp

    haproxy:
        image: haproxy:1.5-alpine
        ports:
            - 8000:8000
        depends_on:
            - log
        links:
            - alice:alice
            - bob:bob
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - ./tmp/log:/dev/log
