version: '3'

services:
    alice-front:
        hostname: alice-front
        build:
            context: ../../
        ports:
            - 5000
        networks:
            - private

    alice-back:
        hostname: alice-back
        build:
            context: ../../
        ports:
            - 5000
        networks:
            - private

    bob:
        hostname: bob
        build:
            context: ../../
        ports:
            - 5000
        networks:
            - private

    log:
        build:
            context: ../../syslog
        ports:
            - 514/udp
        networks:
            - private

    haproxy:
        image: haproxy:1.5-alpine
        ports:
            - 8000:80
        links:
            - alice-front:alice-front
            - alice-back:alice-back
            - bob:bob
            - log:log
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - ./crt:/etc/crt:ro
        networks:
            public:
                aliases:
                    - front.example.com
                    - cdn.example.com
                    - alice.example.com
                    - bob.example.com
            private:

networks:
    public:
    private:
